export const allMenus={
    //业主
    owner:[
        {
            url:'/owner/home',
            key:'ownerHome',
            name:'首页',
        }
    ],
    //商家
    business:[
        {
            url:'/business/home',
            key:'businessHome',
            name:'首页',
        },
        {
            url:'/business/order',
            key:'businessOrder',
            name:'商品发货情况',
        },
        {
            url:'/business/mycommodity',
            key:'businessYycommodity',
            name:'我的商品',
        },
        {
            url:'/business/commoditymng',
            key:'businessCommoditymng',
            name:'商品管理',
        },
        {
            url:'/business/staff',
            key:'businesStaff',
            name:'员工管理',
        }
    ]
}